<?php

namespace App\modelos\informepsicoV1;

use Illuminate\Database\Eloquent\Model;

class datosgeneralesinformePsicoModel extends Model
{
    protected $table = 'datosgeneralesinformePsico';
    protected $primaryKey = 'ID_PSICO_INFORME';
    protected $fillable = [

        'PROYECTO_ID',
        'INFORME_INTRODUCCION',
        'INFORME_OBJETIVOGENERALES',
        'INFORME_OBJETIVOSESPECIFICOS',
        'INFORME_UBICACIONINSTALACION',
        'RUTA_IMAGEN_UBICACION',
        'INFORME_PROCESOINSTALACION',
        'INFORME_ACTIVIDADPRINCIPAL',
        'INFORME_CONCLUSION',
        'INFORME_RESPONSABLE1',
        'INFORME_RESPONSABLE1CARGO',
        'INFORME_RESPONSABLE1DOCUMENTO',
        'INFORME_RESPONSABLE2',
        'INFORME_RESPONSABLE2CARGO',
        'INFORME_RESPONSABLE2DOCUMENTO',
        'DESCRIPCION_METODO',
        'REPORTE_ACONTECIMIENTOS_CONCLUSIONES',
        'REPORTE_AMBIENTE_CONCLUSIONES',
        'REPORTE_CONDICIONES_CONCLUSIONES',
        'REPORTE_FACTORES_CONCLUSIONES',
        'REPORTE_CARGA_CONCLUSIONES',
        'REPORTE_FALTA_CONCLUSIONES',
        'REPORTE_ORGANIZACION_CONCLUSIONES',
        'REPORTE_JORNADA_CONCLUSIONES',
        'REPORTE_INTERFERENCIA_CONCLUSIONES',
        'REPORTE_LIDERAZGORELACIONES_CONCLUSIONES',
        'REPORTE_LIDERAZGO_CONCLUSIONES',
        'REPORTE_RELACIONES_CONCLUSIONES',
        'REPORTE_VIOLENCIA_CONCLUSIONES',
        'REPORTE_ENTORNO_CONCLUSIONES',
        'REPORTE_RECONOCIMIENTO_CONCLUSIONES',
        'REPORTE_INSUFICIENTE_CONCLUSIONES',
        'ANALISIS_GRAFICACALIFICACIONES',
        'ANALISIS_GRAFICA_CATEGORIAS',
        'ANALISIS_GRAFICA_DOMINIOS',
        'ANALISIS_GRAFICA_GUIA1',
        'ANALISIS_GRAFICA_CATAMBIENTE',
        'ANALISIS_GRAFICA_DOMAMBIENTE',
        'ANALISIS_GRAFICA_CATFACTORES',
        'ANALISIS_GRAFICA_DOMFACTORES_1',
        'ANALISIS_GRAFICA_DOMFACTORES_2',
        'ANALISIS_GRAFICA_CATORGANIZACION',
        'ANALISIS_GRAFICA_DOMORGANIZACION_1',
        'ANALISIS_GRAFICA_DOMORGANIZACION_2',
        'ANALISIS_GRAFICA_CATLIDERAZGO',
        'ANALISIS_GRAFICA_DOMLIDERAZGO_1',
        'ANALISIS_GRAFICA_DOMLIDERAZGO_2',
        'ANALISIS_GRAFICA_DOMLIDERAZGO_3',
        'ANALISIS_GRAFICA_CATENTORNO',
        'ANALISIS_GRAFICA_DOMENTORNO_1',
        'ANALISIS_GRAFICA_DOMENTORNO_2',        
        'NIVEL_RIESGO_AMBIENTE',
        'NIVEL_RIESGO_FACTORES',
        'NIVEL_RIESGO_ORGANIZACION',
        'NIVEL_RIESGO_LIDERAZGO',
        'NIVEL_RIESGO_ENTORNO'
    ];
}
