<?php

namespace App\modelos\evaluacionfre;

use Illuminate\Database\Eloquent\Model;

class evaluacionfreModel extends Model
{

    protected $table = 'evaluacion_fre_ergo';
    protected $primaryKey = 'ID_EVALUACION_FRE';
    protected $fillable = [
        'RECO_ID',
        'FICHA_ID',
        'JSON_ACTIVIDADES_FRE',
        'FECHA_EVALUACION_FRE',
        'CAT_DEPARTAMENTO_FRE',
        'EVALUACION_TRABAJADOR',
        'NOMBRE_EMPLEADO_FRE',
        'NO_EMPLEADO_FRE',
        'ULTIMO_GRADO_FRE',
        'INDIQUE_UBICACION_FRE',
        'SEXO_EMPLEADO_FRE',
        'FECHA_NACIMIENTO_FRE',
        'EDAD_EMPLEADO_FRE',
        'REGIMEN_CONTRACTUAL_FRE',
        'JORNADA_EMPLEADO_FRE',
        'TIEMPO_EMPRESA_FRE',
        'ANTIGUEDAD_CATEOGORIA_FRE',
        'PAUSAS_DESCANSO',
        'ENFERMEDAD_MUSCULOESQUELETICA',
        'ENFERMEDAD_MUSCULOESQUELETICA_CUAL',
        'ENFERMEDAD_MUSCULOESQUELETICA_TIEMPO',
        'INCAPACITADO_DOLOR_MUSCULO',
        'FUENTE_ILUMINACION',
        'INTENSIDAD_ILUMINACION',
        'OBSERVACION_ILUMINACION',
        'PERCEPCION_TERMICA',
        'INTENSIDAD_TERMICA',
        'CUAL_PERCEPCION',
        'OBSERVACIONES_TERMICAS',
        'INTENSIDAD_RUIDO',
        'CONTINUIDAD_RUIDO',
        'OBSERVACIONES_RUIDO',
        'INTENSIDAD_VIBRACION',
        'SEGMENTO_VIBRACION',
        'OBSERVACIONES_VIBRACION',
        'PESO_FRE',
        'TALLA_FRE',
        'CUELLO',
        'HOMBRO',
        'HOMBRO_IZQ',
        'HOMBRO_DER',
        'CODO',
        'CODO_IZQ',
        'CODO_DER',
        'MUNECA',
        'MUNECA_IZQ',
        'MUNECA_DER',
        'ESPALDA_ALTA',
        'ESPALDA_BAJA',
        'CADERAS_PIERNAS',
        'RODILLAS',
        'TOBILLOS_PIES',
        'CUELLO_12_MESES',
        'CUELLO_7_DIAS',
        'HOMBRO_12_MESES',
        'HOMBRO_7_DIAS',
        'CODO_12_MESES',
        'CODO_7_DIAS',
        'MUNECA_12_MESES',
        'MUNECA_7_DIAS',
        'ESPALDA_ALTA_12_MESES',
        'ESPALDA_ALTA_7_DIAS',
        'ESPALDA_BAJA_12_MESES',
        'ESPALDA_BAJA_7_DIAS',
        'CADERAS_PIERNAS_12_MESES',
        'CADERAS_PIERNAS_7_DIAS',
        'RODILLAS_12_MESES',
        'RODILLAS_7_DIAS',
        'TOBILLOS_PIES_12_MESES',
        'TOBILLOS_PIES_7_DIAS',
        'COLUMNA_LUMBAR_P1',
        'COLUMNA_LUMBAR_P2',
        'COLUMNA_LUMBAR_P3',
        'COLUMNA_LUMBAR_P4',
        'COLUMNA_LUMBAR_P5_ACTIVIDAD_LABORAL',
        'COLUMNA_LUMBAR_P5_ACTIVIDAD_OCIO',
        'COLUMNA_LUMBAR_P6',
        'COLUMNA_LUMBAR_P7',
        'COLUMNA_LUMBAR_P8',
        'CUELLO_P1',
        'CUELLO_P2',
        'CUELLO_P3',
        'CUELLO_P4',
        'CUELLO_P5_ACTIVIDAD_LABORAL',
        'CUELLO_P5_ACTIVIDAD_OCIO',
        'CUELLO_P6',
        'CUELLO_P7',
        'CUELLO_P8',
        'HOMBRO_P1',
        'HOMBRO_P2',
        'HOMBRO_P3',
        'HOMBRO_P4',
        'HOMBRO_P5_ACTIVIDAD_LABORAL',
        'HOMBRO_P5_ACTIVIDAD_OCIO',
        'HOMBRO_P6',
        'HOMBRO_P7',
        'HOMBRO_P8',
        'FUERZA_MANO_DERECHA',
        'FUERZA_MANO_IZQUIERDA',
        'REQUIERE_FUERZA_MANUAL',
        'TIPO_DOMINANCIA',
        'REALIZA_TAREAS_PIE',
        'BIPEDESTACION_ESTATICA',
        'BIPEDESTACION_DINAMICA',
        'OBSERVACIONES_GENERALES',
        'SUFRIDO_LESION_ACCIDENTE',
        'CUANDO_LESION_ACCIDENTE',
        'CUAL_LESION_ACCIDENTE',
        'ACTIVO',
        'JSON_EQUIPOS_TRABAJO',
        'JSON_FUENTES_TERMICAS',
        'JSON_FUENTES_RUIDO',
        'JSON_FUENTES_VIBRACION',
        'JSON_EPP'


        
    ];
}
